// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ynwBetRuLh31PbeMiDUrg9YtERoocWc',
    appId: '1:15638341073:web:3b49b900544394dc98acf0',
    messagingSenderId: '15638341073',
    projectId: 'property-app-89bf3',
    authDomain: 'property-app-89bf3.firebaseapp.com',
    storageBucket: 'property-app-89bf3.firebasestorage.app',
    measurementId: 'G-TBSM1W4X4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTVGgloKgvZDmxrkNbYjoA4WXKEq_Tjs',
    appId: '1:15638341073:android:b7384104f4dea04998acf0',
    messagingSenderId: '15638341073',
    projectId: 'property-app-89bf3',
    storageBucket: 'property-app-89bf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUNnobF5E6hlWi9TqvvQh3-NyDhWBxDsI',
    appId: '1:15638341073:ios:28b56b95c3e2ffff98acf0',
    messagingSenderId: '15638341073',
    projectId: 'property-app-89bf3',
    storageBucket: 'property-app-89bf3.firebasestorage.app',
    iosBundleId: 'com.example.houserentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUNnobF5E6hlWi9TqvvQh3-NyDhWBxDsI',
    appId: '1:15638341073:ios:28b56b95c3e2ffff98acf0',
    messagingSenderId: '15638341073',
    projectId: 'property-app-89bf3',
    storageBucket: 'property-app-89bf3.firebasestorage.app',
    iosBundleId: 'com.example.houserentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6ynwBetRuLh31PbeMiDUrg9YtERoocWc',
    appId: '1:15638341073:web:ed4fde2e2505ec7e98acf0',
    messagingSenderId: '15638341073',
    projectId: 'property-app-89bf3',
    authDomain: 'property-app-89bf3.firebaseapp.com',
    storageBucket: 'property-app-89bf3.firebasestorage.app',
    measurementId: 'G-5ZBJR2N62H',
  );
}
